/* Hello World Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <pthread.h>

#include "app_priv.h"
#include "pcnt.h"
#include "distance.h"
#include "tcp_server.h"

void app_main()
{
    /* 
      The thread which counts number of pulses generated by speed module 
      i.e. the number of rotations of the wheel
      This is done for measuring the distance covered by the wheel
    */
    pthread_t pcnt_thread;
    pthread_create(&pcnt_thread,NULL,pcnt_initialize,NULL);
    
    /*
      Task for transmitting and receiving the reflected signals of the ultrasonic sensor
    */
    TaskHandle_t xTaskHandle = NULL;
    xTaskCreate(start_measuring_distance,"start_measuring_distance", 4096, NULL, 2, xTaskHandle);
    
    /* Initializing everything for Motor control */
    app_driver_init();

    /* 
      Start the TCP Server which receives commands from the LyraT(which runs the TCP Client) 
      board over socket connection
    */
    start_tcp_server();
}
