/* Pulse counter module - Example

   For other examples please check:
   https://github.com/espressif/esp-idf/tree/master/examples

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/portmacro.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/periph_ctrl.h"
#include "driver/ledc.h"
#include "driver/gpio.h"
#include "driver/pcnt.h"
#include "esp_attr.h"
#include "esp_log.h"
#include "soc/gpio_sig_map.h"

/**
 * TEST CODE BRIEF
 *
 * Use PCNT module to count no of pulses generated by speed module connected to the wheel
 *
 * Functionality of GPIOs used in this example:
 *   - GPIO4 - pulse input pin,
 *   - GPIO5 - control input pin,
 *   - GPIO18 - pulse input pin,
 *
 * Load example, open a serial port to view the message printed on your screen.
 *
 * To do this test, you should connect GPIO18 with GPIO4.
 * GPIO5 is the control signal, you can leave it floating with internal pull up,
 * or connect it to ground. If left floating, the count value will be increasing.
 * If you connect GPIO5 to GND, the count value will be decreasing.
 *
 * An interrupt will be triggered when the counter value:
 *   - reaches 'thresh1' or 'thresh0' value,
 *   - reaches 'l_lim' value or 'h_lim' value,
 *   - will be reset to zero.
 */
#define PCNT_UNIT_LEFT      PCNT_UNIT_0
#define PCNT_UNIT_RIGHT     PCNT_UNIT_1
#define PCNT_INPUT_LEFT  2  // Pulse Input GPIO from encoder module 1 (LEFT WHEEL)
#define PCNT_INPUT_CTRL_IO  5  // Control GPIO HIGH=count up, LOW=count down
#define PCNT_INPUT_RIGHT  18 // Pulse Input GPIO from encoder module 2 (RIGHT WHEEL)

xQueueHandle pcnt_evt_queue;   // A queue to handle pulse counter events
pcnt_isr_handle_t user_isr_handle = NULL; //user's ISR service handle

/* A sample structure to pass events from the PCNT
 * interrupt handler to the main program.
 */
typedef struct {
    int unit;  // the PCNT unit that originated an interrupt
    uint32_t status; // information on the event type that caused the interrupt
} pcnt_evt_t;

/* Decode what PCNT's unit originated an interrupt
 * and pass this information together with the event type
 * the main program using a queue.
 */
static void IRAM_ATTR pcnt_intr_handler_left(void *arg)
{
    uint32_t intr_status = PCNT.int_st.val;
    int i;
    pcnt_evt_t evt;
    portBASE_TYPE HPTaskAwoken = pdFALSE;

    for (i = 0; i < PCNT_UNIT_MAX; i++) {
        if (intr_status & (BIT(i))) {
            evt.unit = i;
            /* Save the PCNT event type that caused an interrupt
               to pass it to the main program */
            evt.status = PCNT.status_unit[i].val;
            PCNT.int_clr.val = BIT(i);
            xQueueSendFromISR(pcnt_evt_queue, &evt, &HPTaskAwoken);
            if (HPTaskAwoken == pdTRUE) {
                portYIELD_FROM_ISR();
            }
        }
    }
}

/* 
*  Interrupt handler for unit 1
*/
static void IRAM_ATTR pcnt_intr_handler_right(void *arg)
{
    uint32_t intr_status = PCNT.int_st.val;
    int i;
    pcnt_evt_t evt;
    portBASE_TYPE HPTaskAwoken = pdFALSE;

    for (i = 0; i < PCNT_UNIT_MAX; i++) {
        if (intr_status & (BIT(i))) {
            evt.unit = i;
            /* Save the PCNT event type that caused an interrupt
               to pass it to the main program */
            evt.status = PCNT.status_unit[i].val;
            PCNT.int_clr.val = BIT(i);
            xQueueSendFromISR(pcnt_evt_queue, &evt, &HPTaskAwoken);
            if (HPTaskAwoken == pdTRUE) {
                portYIELD_FROM_ISR();
            }
        }
    }
}


/* Initialize PCNT functions:
 *  - configure and initialize PCNT
 *  - set up the input filter
 *  - set up the counter events to watch
 */
static void pcnt_configure(void)
{
    /* Prepare configuration for the LEFT PCNT unit */
    pcnt_config_t pcnt_config_left = {
        // Set PCNT input signal and control GPIOs
        .pulse_gpio_num = PCNT_INPUT_LEFT,
        .ctrl_gpio_num = PCNT_INPUT_CTRL_IO,
        .channel = PCNT_CHANNEL_0,
        .unit = PCNT_UNIT_LEFT,
        // What to do on the positive / negative edge of pulse input?
        .pos_mode = PCNT_COUNT_INC,   // Count up on the positive edge
        .neg_mode = PCNT_COUNT_DIS,   // Keep the counter value on the negative edge
        // What to do when control input is low or high?
        .lctrl_mode = PCNT_MODE_KEEP,    // Keep the primary counter mode if high
        .hctrl_mode = PCNT_MODE_REVERSE, // Reverse counting direction if low
    };

    /* Prepare configuration for the RIGHT PCNT unit */
    pcnt_config_t pcnt_config_right = {
        // Set PCNT input signal and control GPIOs
        .pulse_gpio_num = PCNT_INPUT_RIGHT,
        .ctrl_gpio_num = PCNT_INPUT_CTRL_IO,
        .channel = PCNT_CHANNEL_0,      //CHANGE IF REQUIRED ###############################################
        .unit = PCNT_UNIT_RIGHT,         //CHANGE IF REQUIRED ###############################################
        // What to do on the positive / negative edge of pulse input?
        .pos_mode = PCNT_COUNT_INC,   // Count up on the positive edge
        .neg_mode = PCNT_COUNT_DIS,   // Keep the counter value on the negative edge
        // What to do when control input is low or high?
        .lctrl_mode = PCNT_MODE_KEEP,    // Keep the primary counter mode if high
        .hctrl_mode = PCNT_MODE_REVERSE, // Reverse counting direction if low
    };

    /* Initialize both the PCNT units */
    pcnt_unit_config(&pcnt_config_left);
    pcnt_unit_config(&pcnt_config_right);

    /* Configure and enable the input filter */
    pcnt_set_filter_value(PCNT_UNIT_LEFT, 100);
    pcnt_filter_enable(PCNT_UNIT_LEFT);
    pcnt_set_filter_value(PCNT_UNIT_RIGHT, 100);
    pcnt_filter_enable(PCNT_UNIT_RIGHT);

    /* Set threshold 0 and 1 values and enable events to watch */

    // pcnt_set_event_value(PCNT_UNIT, PCNT_EVT_THRES_1, PCNT_THRESH1_VAL);
    // pcnt_event_enable(PCNT_UNIT, PCNT_EVT_THRES_1);
    // pcnt_set_event_value(PCNT_UNIT, PCNT_EVT_THRES_0, PCNT_THRESH0_VAL);
    // pcnt_event_enable(PCNT_UNIT, PCNT_EVT_THRES_0);

    /* Enable events on zero, maximum and minimum limit values */
    // pcnt_event_enable(PCNT_UNIT, PCNT_EVT_ZERO);
    // pcnt_event_enable(PCNT_UNIT, PCNT_EVT_H_LIM);
    // pcnt_event_enable(PCNT_UNIT, PCNT_EVT_L_LIM);

    //SETTING INTERRUPT HANDLER FOR UNIT 0
    /* Initialize PCNT's counter */
    pcnt_counter_pause(PCNT_UNIT_LEFT);
    pcnt_counter_clear(PCNT_UNIT_LEFT);

    /* Register ISR handler and enable interrupts for PCNT unit */
    pcnt_isr_register(pcnt_intr_handler_left, NULL, 0, &user_isr_handle);
    pcnt_intr_enable(PCNT_UNIT_LEFT);

    /* Everything is set up, now go to counting */
    pcnt_counter_resume(PCNT_UNIT_LEFT);


    //SETTING INTERRUPT HANDLER FOR UNIT 1
    /* Initialize PCNT's counter */
    pcnt_counter_pause(PCNT_UNIT_RIGHT);
    pcnt_counter_clear(PCNT_UNIT_RIGHT);

    /* Register ISR handler and enable interrupts for PCNT unit */
    pcnt_isr_register(pcnt_intr_handler_right, NULL, 0, &user_isr_handle);
    pcnt_intr_enable(PCNT_UNIT_RIGHT);

    /* Everything is set up, now go to counting */
    pcnt_counter_resume(PCNT_UNIT_RIGHT);
}

int16_t get_count_left()
{
    int16_t count;
    pcnt_get_counter_value(PCNT_UNIT_LEFT, &count);
    return count;
}

int16_t get_count_right()
{
    int16_t count;
    pcnt_get_counter_value(PCNT_UNIT_RIGHT, &count);
    return count;
}

void *pcnt_initialize(void *arg)
{
    /* Initialize PCNT event queue and PCNT functions */
    pcnt_evt_queue = xQueueCreate(1000, sizeof(pcnt_evt_t));
    pcnt_configure();

    int16_t count = 0;
    pcnt_evt_t evt;
    portBASE_TYPE res;
    while (1) {
        /* Wait for the event information passed from PCNT's interrupt handler.
         * Once received, decode the event type and print it on the serial monitor.
         */
        // res = xQueueReceive(pcnt_evt_queue, &evt, 10 / portTICK_PERIOD_MS);
        vTaskDelay(500/portTICK_PERIOD_MS);
        pcnt_get_counter_value(PCNT_UNIT_LEFT, &count);
        printf("Current left counter value :%d\n", count);
        pcnt_get_counter_value(PCNT_UNIT_RIGHT, &count);
        printf("Current right counter value :%d\n", count);
        
    }
    if(user_isr_handle) {
        //Free the ISR service handle.
        esp_intr_free(user_isr_handle);
        user_isr_handle = NULL;
    }
}

void reset_counters()
{
    pcnt_counter_clear(PCNT_UNIT_LEFT);
    pcnt_counter_clear(PCNT_UNIT_RIGHT);
}